[package]
name = "ply"
version = "0.1.0"
edition = "2021"

[dependencies]
ply = {version='*', package='ply-rs'}

[patch.'crates-io']
ply = {git='https://github.com/Matthias-Fauconneau/ply-rs', package='ply-rs'}
#ply = {path='../ply-rs', package='ply-rs'}
